### ISSUE TITLE
Summer 2019 Announcement

### ISSUE THREAD

**Issue by wbadry** [wbadry/MTE403#1]
This is where we can communicate during course activities.

**Comment by AhemdAlashry** [comment]
Confirmed

**Comment by Mustafa58541** [comment]
دكتور وليد انا ممتحنتش الكويزات بسبب
ان حضرتك قولتلي يوم السبت(8/3)ان حضرتك هتتفق معايا يوم هتمتحني فيه   كل الكويزات
لكن حضرتك لم تاتي هذا اليوم  
علما بان انا لااحضر السكشن الاساس بسب تعارض مع ماده الروبوتيكس

**Comment by wbadry** [comment]
مفيش مشكلة بعد العيد سيتم عمل الامتحانات ليك.

**Comment by Mustafa58541** [comment]
> 
> 
> مفيش مشكلة بعد العيد سيتم عمل الامتحانات ليك.
 
بس اعمال السنه هتتسلم قبل العيد

**Comment by wbadry** [comment]
> 
> 
> > مفيش مشكلة بعد العيد سيتم عمل الامتحانات ليك.
> 
> بس اعمال السنه هتتسلم قبل العيد

لحد علمي أنا اللي عارف امتى

**Comment by wbadry** [comment]
@Mustafa58541 Prepare to do your quizzes on Wednesday 14/08/2019 10:00 AM inshallah

**Comment by mustafamo** [comment]
باشمهندس لو سمحت ممكن تراجع تجميعة درجاتى ! 
id\ 70442

**Comment by wbadry** [comment]
@Mustafa58541 Your total marks are 51/60 [[midterm : 22/30 , CW: 29/30 ]] 
@Mustafa58541 Your total is 36/60 [midterm : 18/30 , CW: 18/30 ]

Marks were reviewed and delivered to the faculty. File any complaints if exists directly to the course lecturer.
